import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'app_name': 'ScoreDuck',
          'common_cancel': 'Cancel',
          'common_done': 'Done',
          'common_save': 'Save',
          'common_delete': 'Delete',
          'common_confirm': 'Confirm',
          'common_edit': 'Edit',
          'common_share': 'Share',
          'common_unknown': 'Unknown',
          'home_tab_title': 'Games',
          'home_title': 'ScoreDuck',
          'home_no_games': 'No Games',
          'home_start_first_game': 'Start your first game',
          'home_create_game': 'New Game',
          'home_game_count': '{}' ' Games',
          'home_player_count': '{}' ' Players',
          'create_game_title': 'Create Game',
          'create_game_start': 'Start',
          'create_game_basic_info': 'Basic Info',
          'create_game_game_name': 'Game Name',
          'create_game_game_name_placeholder': 'Enter game name',
          'create_game_player_count': 'Players',
          'create_game_player_list': 'Player List',
          'create_game_player_name_placeholder': 'Enter player name',
          'create_game_default_game_name': 'New Game',
          'create_game_default_player_name': 'Player {}',
          'game_detail_found_no_game': 'Game not found',
          'game_detail_leaderboard': 'Leaderboard',
          'game_detail_current_score': 'Live Score',
          'game_detail_round_count': '{}' ' Rounds',
          'game_detail_leading': 'Leading',
          'game_detail_round_n': 'Round {}',
          'game_detail_no_rounds': 'No Records',
          'game_detail_start_scoring': 'Tap the button to start scoring',
          'game_detail_share_text': 'Check out our live score!',
          'game_detail_add_round': 'Record Round',
          'game_detail_edit_round': 'Edit Round',
          'game_detail_base_score': 'Base Score',
          'game_detail_step_size': 'Step Size',
          'game_detail_current_round_score': 'Round Score',
          'settings_tab_title': 'Settings',
          'settings_title': 'Settings',
          'settings_appearance': 'Appearance',
          'settings_theme_mode': 'Theme Mode',
          'settings_theme_system': 'System',
          'settings_theme_light': 'Light',
          'settings_theme_dark': 'Dark',
          'settings_language_title': 'Language',
          'settings_language_en': 'English',
          'settings_language_zh_Hans': 'Simplified Chinese',
          'settings_language_zh_Hant': 'Traditional Chinese',
          'settings_language_es': 'Spanish',
          'settings_language_fr': 'French',
          'settings_language_de': 'German',
          'settings_language_hi': 'Hindi',
          'settings_language_ar': 'Arabic',
          'settings_language_system': 'System',
          'settings_about_title': 'About',
          'settings_about_about_app': 'About ScoreDuck',
          'settings_about_version': 'Version',
          'settings_support_title': 'Feedback & Support',
          'settings_support_feedback': 'Feedback',
          'settings_support_feedback_subject': 'ScoreDuckAPP Feedback (Version: {version})',
          'settings_support_more_apps': 'More Apps',
          'settings_support_follow_author': 'Follow Author',
          'settings_danger_zone_title': 'Danger Zone',
          'settings_danger_zone_clear_data': 'Clear All Data',
          'settings_danger_zone_clear_confirm_title': 'Clear Data',
          'settings_danger_zone_clear_confirm_content':
              'Are you sure you want to delete all records? This cannot be undone.',
          'about_description':
              'ScoreDuck is a simple and elegant score tracker. Dedicated to providing you with the purest and most efficient experience.',
          'about_privacy_safety': 'Privacy & Safety',
          'about_privacy_offline': 'Runs offline, no internet permission',
          'about_privacy_no_cloud': 'Zero cloud upload, no server involved',
          'about_privacy_local': 'Local storage, your data belongs to you',
          'about_feedback_support': 'Feedback & Support',
        },
        'zh-Hans': {
          'app_name': '记分鸭',
          'common_cancel': '取消',
          'common_done': '完成',
          'common_save': '保存',
          'common_delete': '删除',
          'common_confirm': '确认',
          'common_edit': '编辑',
          'common_share': '分享',
          'common_unknown': '未知',
          'home_tab_title': '比赛',
          'home_title': '记分鸭',
          'home_no_games': '暂无比赛',
          'home_start_first_game': '开启你的第一场比赛吧',
          'home_create_game': '新建比赛',
          'home_game_count': '{}' ' 场比赛',
          'home_player_count': '{}' ' 位玩家',
          'create_game_title': '创建比赛',
          'create_game_start': '开始',
          'create_game_basic_info': '基本信息',
          'create_game_game_name': '比赛名称',
          'create_game_game_name_placeholder': '请输入比赛名称',
          'create_game_player_count': '玩家人数',
          'create_game_player_list': '玩家列表',
          'create_game_player_name_placeholder': '请输入玩家名字',
          'create_game_default_game_name': '新比赛',
          'create_game_default_player_name': '玩家 {}',
          'game_detail_found_no_game': '未找到比赛',
          'game_detail_leaderboard': '排行榜',
          'game_detail_current_score': '当前比分',
          'game_detail_round_count': '已进行 {}' ' 局',
          'game_detail_leading': '领跑',
          'game_detail_round_n': '第 {}' ' 局',
          'game_detail_no_rounds': '暂无对局记录',
          'game_detail_start_scoring': '点击右下角按钮开始记分',
          'game_detail_share_text': '这是我们的比赛实时比分！',
          'game_detail_add_round': '记录本局',
          'game_detail_edit_round': '修改记录',
          'game_detail_base_score': '基础分',
          'game_detail_step_size': '增减步长',
          'game_detail_current_round_score': '本局得分',
          'settings_tab_title': '设置',
          'settings_title': '设置',
          'settings_appearance': '外观',
          'settings_theme_mode': '主题模式',
          'settings_theme_system': '系统',
          'settings_theme_light': '浅色',
          'settings_theme_dark': '深色',
          'settings_language_title': '语言',
          'settings_language_en': '英语',
          'settings_language_zh_Hans': '简体中文',
          'settings_language_zh_Hant': '繁體中文',
          'settings_language_es': '西班牙语',
          'settings_language_fr': '法语',
          'settings_language_de': '德语',
          'settings_language_hi': '印地语',
          'settings_language_ar': '阿拉伯语',
          'settings_language_system': '跟随系统',
          'settings_about_title': '关于',
          'settings_about_about_app': '关于记分鸭',
          'settings_about_version': '当前版本',
          'settings_support_title': '反馈与支持',
          'settings_support_feedback': '意见反馈',
          'settings_support_feedback_subject': '记分鸭意见反馈 (版本: {version})',
          'settings_support_more_apps': '更多应用',
          'settings_support_follow_author': '关注作者',
          'settings_danger_zone_title': '危险区域',
          'settings_danger_zone_clear_data': '清除所有数据',
          'settings_danger_zone_clear_confirm_title': '确认清除',
          'settings_danger_zone_clear_confirm_content':
              '确定要删除所有比赛记录吗？此操作无法撤销。',
          'about_description':
              '记分鸭是一款简单、优雅的比赛记分工具。致力于为您提供最纯净、高效的记分体验。',
          'about_privacy_safety': '隐私与安全',
          'about_privacy_offline': '完全离线运行，无需互联网权限',
          'about_privacy_no_cloud': '零云端上传，数据不经过服务器',
          'about_privacy_local': '本地安全存储，您的数据仅属于您',
          'about_feedback_support': '反馈与支持',
        },
        'zh-Hant': {
          'app_name': '記分鴨',
          'common_cancel': '取消',
          'common_done': '完成',
          'common_save': '儲存',
          'common_delete': '刪除',
          'common_confirm': '確認',
          'common_edit': '編輯',
          'common_share': '分享',
          'common_unknown': '未知',
          'home_tab_title': '比賽',
          'home_title': '記分鴨',
          'home_no_games': '暫無比賽',
          'home_start_first_game': '開啟你的第一場比賽吧',
          'home_create_game': '新建比賽',
          'home_game_count': '{}' ' 場比賽',
          'home_player_count': '{}' ' 位玩家',
          'create_game_title': '建立比賽',
          'create_game_start': '開始',
          'create_game_basic_info': '基本資訊',
          'create_game_game_name': '比賽名稱',
          'create_game_game_name_placeholder': '請輸入比賽名稱',
          'create_game_player_count': '玩家人數',
          'create_game_player_list': '玩家列表',
          'create_game_player_name_placeholder': '請輸入玩家名字',
          'create_game_default_game_name': '新比賽',
          'create_game_default_player_name': '玩家 {}',
          'game_detail_found_no_game': '未找到比賽',
          'game_detail_leaderboard': '排行榜',
          'game_detail_current_score': '目前比分',
          'game_detail_round_count': '已進行 {}' ' 局',
          'game_detail_leading': '領跑',
          'game_detail_round_n': '第 {}' ' 局',
          'game_detail_no_rounds': '暫無對局記錄',
          'game_detail_start_scoring': '點擊右下角按鈕開始記分',
          'game_detail_share_text': '這是我們的比賽即時比分！',
          'game_detail_add_round': '記錄本局',
          'game_detail_edit_round': '修改記錄',
          'game_detail_base_score': '基礎分',
          'game_detail_step_size': '增減步長',
          'game_detail_current_round_score': '本局得分',
          'settings_tab_title': '設定',
          'settings_title': '設定',
          'settings_appearance': '外觀',
          'settings_theme_mode': '主題模式',
          'settings_theme_system': '系統',
          'settings_theme_light': '淺色',
          'settings_theme_dark': '深色',
          'settings_language_title': '語言',
          'settings_language_en': '英語',
          'settings_language_zh_Hans': '簡體中文',
          'settings_language_zh_Hant': '繁體中文',
          'settings_language_es': '西班牙語',
          'settings_language_fr': '法語',
          'settings_language_de': '德語',
          'settings_language_hi': '印地語',
          'settings_language_ar': '阿拉伯語',
          'settings_language_system': '跟隨系統',
          'settings_about_title': '關於',
          'settings_about_about_app': '關於記分鴨',
          'settings_about_version': '目前版本',
          'settings_support_title': '回饋與支援',
          'settings_support_feedback': '意見回饋',
          'settings_support_feedback_subject': '記分鴨意見回饋 (版本: {version})',
          'settings_support_more_apps': '更多應用',
          'settings_support_follow_author': '關注作者',
          'settings_danger_zone_title': '危險區域',
          'settings_danger_zone_clear_data': '清除所有資料',
          'settings_danger_zone_clear_confirm_title': '確認清除',
          'settings_danger_zone_clear_confirm_content':
              '確定要刪除所有比賽記錄嗎？此操作無法撤銷。',
          'about_description':
              '記分鴨是一款簡單、優雅的比賽記分工具。致力於為您提供最純淨、高效的記分體驗。',
          'about_privacy_safety': '隱私與安全',
          'about_privacy_offline': '完全離線運行，無需網路權限',
          'about_privacy_no_cloud': '零雲端上傳，資料不經過伺服器',
          'about_privacy_local': '本地安全存儲，您的資料僅屬於您',
          'about_feedback_support': '回饋與支援',
        },
        'es': {
          'app_name': 'ScoreDuck',
          'common_cancel': 'Cancelar',
          'common_done': 'Hecho',
          'common_save': 'Guardar',
          'common_delete': 'Eliminar',
          'common_confirm': 'Confirmar',
          'common_edit': 'Editar',
          'common_share': 'Compartir',
          'common_unknown': 'Desconocido',
          'home_tab_title': 'Juegos',
          'home_title': 'ScoreDuck',
          'home_no_games': 'No hay juegos',
          'home_start_first_game': 'Empieza tu primer juego',
          'home_create_game': 'Nuevo juego',
          'home_game_count': '{}' ' Juegos',
          'home_player_count': '{}' ' Jugadores',
          'create_game_title': 'Crear juego',
          'create_game_start': 'Empezar',
          'create_game_basic_info': 'Información básica',
          'create_game_game_name': 'Nombre del juego',
          'create_game_game_name_placeholder': 'Introduce el nombre del juego',
          'create_game_player_count': 'Jugadores',
          'create_game_player_list': 'Lista de jugadores',
          'create_game_player_name_placeholder': 'Introduce el nombre del jugador',
          'create_game_default_game_name': 'Nuevo juego',
          'create_game_default_player_name': 'Jugador {}',
          'game_detail_found_no_game': 'Juego no encontrado',
          'game_detail_leaderboard': 'Clasificación',
          'game_detail_current_score': 'Puntuación en vivo',
          'game_detail_round_count': '{}' ' Rondas',
          'game_detail_leading': 'Líder',
          'game_detail_round_n': 'Ronda {}',
          'game_detail_no_rounds': 'No hay registros',
          'game_detail_start_scoring': 'Toca el botón para empezar a puntuar',
          'game_detail_share_text': '¡Mira nuestra puntuación en vivo!',
          'game_detail_add_round': 'Registrar ronda',
          'game_detail_edit_round': 'Editar ronda',
          'game_detail_base_score': 'Puntuación base',
          'game_detail_step_size': 'Tamaño del paso',
          'game_detail_current_round_score': 'Puntuación de la ronda',
          'settings_tab_title': 'Ajustes',
          'settings_title': 'Ajustes',
          'settings_appearance': 'Apariencia',
          'settings_theme_mode': 'Modo tema',
          'settings_theme_system': 'Sistema',
          'settings_theme_light': 'Claro',
          'settings_theme_dark': 'Oscuro',
          'settings_language_title': 'Idioma',
          'settings_language_en': 'English',
          'settings_language_zh_Hans': 'Simplified Chinese',
          'settings_language_zh_Hant': 'Traditional Chinese',
          'settings_language_es': 'Español',
          'settings_language_fr': 'Francés',
          'settings_language_de': 'Alemán',
          'settings_language_hi': 'Hindi',
          'settings_language_ar': 'Árabe',
          'settings_language_system': 'Sistema',
          'settings_about_title': 'Acerca de',
          'settings_about_about_app': 'Acerca de ScoreDuck',
          'settings_about_version': 'Versión',
          'settings_support_title': 'Comentarios y soporte',
          'settings_support_feedback': 'Comentarios',
          'settings_support_feedback_subject': 'ScoreDuckAPP Comentarios (Versión: {version})',
          'settings_support_more_apps': 'Más aplicaciones',
          'settings_support_follow_author': 'Seguir al autor',
          'settings_danger_zone_title': 'Zona de peligro',
          'settings_danger_zone_clear_data': 'Borrar todos los datos',
          'settings_danger_zone_clear_confirm_title': 'Borrar datos',
          'settings_danger_zone_clear_confirm_content':
              '¿Estás seguro de que quieres eliminar todos los registros? Esto no se puede deshacer.',
          'about_description':
              'ScoreDuck es un rastreador de puntuación simple y elegante. Dedicado a brindarte la experiencia más pura y eficiente.',
          'about_privacy_safety': 'Privacidad y seguridad',
          'about_privacy_offline':
              'Funciona sin conexión, no requiere permiso de internet',
          'about_privacy_no_cloud':
              'Cero carga en la nube, no hay servidor involucrado',
          'about_privacy_local':
              'Almacenamiento local, tus datos te pertenecen',
          'about_feedback_support': 'Comentarios y soporte',
        },
        'fr': {
          'app_name': 'ScoreDuck',
          'common_cancel': 'Annuler',
          'common_done': 'Terminé',
          'common_save': 'Enregistrer',
          'common_delete': 'Supprimer',
          'common_confirm': 'Confirmer',
          'common_edit': 'Modifier',
          'common_share': 'Partager',
          'common_unknown': 'Inconnu',
          'home_tab_title': 'Jeux',
          'home_title': 'ScoreDuck',
          'home_no_games': 'Pas de jeux',
          'home_start_first_game': 'Commencez votre premier jeu',
          'home_create_game': 'Nouveau jeu',
          'home_game_count': '{}' ' Jeux',
          'home_player_count': '{}' ' Joueurs',
          'create_game_title': 'Créer un jeu',
          'create_game_start': 'Commencer',
          'create_game_basic_info': 'Informations de base',
          'create_game_game_name': 'Nom du jeu',
          'create_game_game_name_placeholder': 'Entrez le nom du jeu',
          'create_game_player_count': 'Joueurs',
          'create_game_player_list': 'Liste des joueurs',
          'create_game_player_name_placeholder': 'Entrez le nom du joueur',
          'create_game_default_game_name': 'Nouveau jeu',
          'create_game_default_player_name': 'Joueur {}',
          'game_detail_found_no_game': 'Jeu non trouvé',
          'game_detail_leaderboard': 'Classement',
          'game_detail_current_score': 'Score en direct',
          'game_detail_round_count': '{}' ' Tours',
          'game_detail_leading': 'En tête',
          'game_detail_round_n': 'Tour {}',
          'game_detail_no_rounds': 'Aucun enregistrement',
          'game_detail_start_scoring':
              'Appuyez sur le bouton pour commencer à marquer',
          'game_detail_share_text': 'Découvrez notre score en direct !',
          'game_detail_add_round': 'Enregistrer le tour',
          'game_detail_edit_round': 'Modifier le tour',
          'game_detail_base_score': 'Score de base',
          'game_detail_step_size': 'Taille du pas',
          'game_detail_current_round_score': 'Score du tour',
          'settings_tab_title': 'Paramètres',
          'settings_title': 'Paramètres',
          'settings_appearance': 'Apparence',
          'settings_theme_mode': 'Mode thème',
          'settings_theme_system': 'Système',
          'settings_theme_light': 'Clair',
          'settings_theme_dark': 'Sombre',
          'settings_language_title': 'Langue',
          'settings_language_en': 'English',
          'settings_language_zh_Hans': 'Simplified Chinese',
          'settings_language_zh_Hant': 'Traditional Chinese',
          'settings_language_es': 'Espagnol',
          'settings_language_fr': 'Français',
          'settings_language_de': 'Allemand',
          'settings_language_hi': 'Hindi',
          'settings_language_ar': 'Arabe',
          'settings_language_system': 'Système',
          'settings_about_title': 'À propos',
          'settings_about_about_app': 'À propos de ScoreDuck',
          'settings_about_version': 'Version',
          'settings_support_title': 'Commentaires et assistance',
          'settings_support_feedback': 'Commentaires',
          'settings_support_feedback_subject': 'ScoreDuckAPP Commentaires (Version: {version})',
          'settings_support_more_apps': 'Plus d\'applications',
          'settings_support_follow_author': 'Suivre l' 'auteur',
          'settings_danger_zone_title': 'Zone de danger',
          'settings_danger_zone_clear_data': 'Effacer toutes les données',
          'settings_danger_zone_clear_confirm_title': 'Effacer les données',
          'settings_danger_zone_clear_confirm_content':
              'Êtes-vous sûr de vouloir supprimer tous les enregistrements ? Cette action est irréversible.',
          'about_description':
              'ScoreDuck est un simple et élégant suivi de score. Dédié à vous offrir l' 'expérience la plus pure et la plus efficace.',
          'about_privacy_safety': 'Confidentialité et sécurité',
          'about_privacy_offline':
              'Fonctionne hors ligne, aucune autorisation internet',
          'about_privacy_no_cloud':
              'Zéro téléchargement cloud, aucun serveur impliqué',
          'about_privacy_local':
              'Stockage local, vos données vous appartiennent',
          'about_feedback_support': 'Commentaires et assistance',
        },
        'de': {
          'app_name': 'ScoreDuck',
          'common_cancel': 'Abbrechen',
          'common_done': 'Fertig',
          'common_save': 'Speichern',
          'common_delete': 'Löschen',
          'common_confirm': 'Bestätigen',
          'common_edit': 'Bearbeiten',
          'common_share': 'Teilen',
          'common_unknown': 'Unbekannt',
          'home_tab_title': 'Spiele',
          'home_title': 'ScoreDuck',
          'home_no_games': 'Keine Spiele',
          'home_start_first_game': 'Starten Sie Ihr erstes Spiel',
          'home_create_game': 'Neues Spiel',
          'home_game_count': '{}' ' Spiele',
          'home_player_count': '{}' ' Spieler',
          'create_game_title': 'Spiel erstellen',
          'create_game_start': 'Starten',
          'create_game_basic_info': 'Grundlegende Informationen',
          'create_game_game_name': 'Spielname',
          'create_game_game_name_placeholder': 'Geben Sie den Spielnamen ein',
          'create_game_player_count': 'Spieler',
          'create_game_player_list': 'Spielerliste',
          'create_game_player_name_placeholder': 'Geben Sie den Spielernamen ein',
          'create_game_default_game_name': 'Neues Spiel',
          'create_game_default_player_name': 'Spieler {}',
          'game_detail_found_no_game': 'Spiel nicht gefunden',
          'game_detail_leaderboard': 'Bestenliste',
          'game_detail_current_score': 'Live-Ergebnis',
          'game_detail_round_count': '{}' ' Runden',
          'game_detail_leading': 'Führend',
          'game_detail_round_n': 'Runde {}',
          'game_detail_no_rounds': 'Keine Aufzeichnungen',
          'game_detail_start_scoring':
              'Tippen Sie auf die Schaltfläche, um mit der Wertung zu beginnen',
          'game_detail_share_text': 'Schauen Sie sich unser Live-Ergebnis an!',
          'game_detail_add_round': 'Runde aufzeichnen',
          'game_detail_edit_round': 'Runde bearbeiten',
          'game_detail_base_score': 'Grundpunktzahl',
          'game_detail_step_size': 'Schrittgröße',
          'game_detail_current_round_score': 'Rundenergebnis',
          'settings_tab_title': 'Einstellungen',
          'settings_title': 'Einstellungen',
          'settings_appearance': 'Aussehen',
          'settings_theme_mode': 'Themenmodus',
          'settings_theme_system': 'System',
          'settings_theme_light': 'Hell',
          'settings_theme_dark': 'Dunkel',
          'settings_language_title': 'Sprache',
          'settings_language_en': 'English',
          'settings_language_zh_Hans': 'Simplified Chinese',
          'settings_language_zh_Hant': 'Traditional Chinese',
          'settings_language_es': 'Spanisch',
          'settings_language_fr': 'Französisch',
          'settings_language_de': 'Deutsch',
          'settings_language_hi': 'Hindi',
          'settings_language_ar': 'Arabisch',
          'settings_language_system': 'System',
          'settings_about_title': 'Über',
          'settings_about_about_app': 'Über ScoreDuck',
          'settings_about_version': 'Version',
          'settings_support_title': 'Feedback & Support',
          'settings_support_feedback': 'Feedback',
          'settings_support_feedback_subject': 'ScoreDuckAPP Feedback (Version: {version})',
          'settings_support_more_apps': 'Mehr Apps',
          'settings_support_follow_author': 'Autor folgen',
          'settings_danger_zone_title': 'Gefahrenzone',
          'settings_danger_zone_clear_data': 'Alle Daten löschen',
          'settings_danger_zone_clear_confirm_title': 'Daten löschen',
          'settings_danger_zone_clear_confirm_content':
              'Möchten Sie wirklich alle Aufzeichnungen löschen? Dies kann nicht rückgängig gemacht werden.',
          'about_description':
              'ScoreDuck ist ein einfacher und eleganter Punktezähler. Wir sind bestrebt, Ihnen die reinste und effizienteste Erfahrung zu bieten.',
          'about_privacy_safety': 'Datenschutz & Sicherheit',
          'about_privacy_offline':
              'Läuft offline, keine Internetberechtigung',
          'about_privacy_no_cloud': 'Kein Cloud-Upload, kein Server beteiligt',
          'about_privacy_local': 'Lokale Speicherung, Ihre Daten gehören Ihnen',
          'about_feedback_support': 'Feedback & Support',
        },
        'hi': {
          'app_name': 'स्कोरडक',
          'common_cancel': 'रद्द करें',
          'common_done': 'हो गया',
          'common_save': 'सहेजें',
          'common_delete': 'मिटाएँ',
          'common_confirm': 'पुष्टि करें',
          'common_edit': 'संपादित करें',
          'common_share': 'साझा करें',
          'common_unknown': 'अज्ञात',
          'home_tab_title': 'खेल',
          'home_title': 'स्कोरडक',
          'home_no_games': 'कोई खेल नहीं',
          'home_start_first_game': 'अपना पहला खेल शुरू करें',
          'home_create_game': 'नया खेल',
          'home_game_count': '{}' ' खेल',
          'home_player_count': '{}' ' खिलाड़ी',
          'create_game_title': 'खेल बनाएँ',
          'create_game_start': 'शुरू करें',
          'create_game_basic_info': 'बुनियादी जानकारी',
          'create_game_game_name': 'खेल का नाम',
          'create_game_game_name_placeholder': 'खेल का नाम दर्ज करें',
          'create_game_player_count': 'खिलाड़ी',
          'create_game_player_list': 'खिलाड़ी सूची',
          'create_game_player_name_placeholder': 'खिलाड़ी का नाम दर्ज करें',
          'create_game_default_game_name': 'नया खेल',
          'create_game_default_player_name': 'खिलाड़ी {}',
          'game_detail_found_no_game': 'खेल नहीं मिला',
          'game_detail_leaderboard': 'लीडरबोर्ड',
          'game_detail_current_score': 'लाइव स्कोर',
          'game_detail_round_count': '{}' ' राउंड',
          'game_detail_leading': 'अग्रणी',
          'game_detail_round_n': 'राउंड {}',
          'game_detail_no_rounds': 'कोई रिकॉर्ड नहीं',
          'game_detail_start_scoring': 'स्कोर करना शुरू करने के लिए बटन पर टैप करें',
          'game_detail_share_text': 'हमारा लाइव स्कोर देखें!',
          'game_detail_add_round': 'राउंड रिकॉर्ड करें',
          'game_detail_edit_round': 'राउंड संपादित करें',
          'game_detail_base_score': 'बेस स्कोर',
          'game_detail_step_size': 'स्टेप आकार',
          'game_detail_current_round_score': 'राउंड स्कोर',
          'settings_tab_title': 'सेटिंग्स',
          'settings_title': 'सेटिंग्स',
          'settings_appearance': 'दिखावट',
          'settings_theme_mode': 'थीम मोड',
          'settings_theme_system': 'सिस्टम',
          'settings_theme_light': 'लाइट',
          'settings_theme_dark': 'डार्क',
          'settings_language_title': 'भाषा',
          'settings_language_en': 'English',
          'settings_language_zh_Hans': 'Simplified Chinese',
          'settings_language_zh_Hant': 'Traditional Chinese',
          'settings_language_es': 'Español',
          'settings_language_fr': 'Francés',
          'settings_language_de': 'जर्मन',
          'settings_language_hi': 'हिन्दी',
          'settings_language_ar': 'अरबी',
          'settings_language_system': 'सिस्टम',
          'settings_about_title': 'के बारे में',
          'settings_about_about_app': 'स्कोरडक के बारे में',
          'settings_about_version': 'संस्करण',
          'settings_support_title': 'प्रतिक्रिया और समर्थन',
          'settings_support_feedback': 'प्रतिक्रिया',
          'settings_support_feedback_subject': 'स्कोरडक ऐप प्रतिक्रिया (संस्करण: {version})',
          'settings_support_more_apps': 'अधिक ऐप',
          'settings_support_follow_author': 'लेखक का अनुसरण करें',
          'settings_danger_zone_title': 'खतरनाक क्षेत्र',
          'settings_danger_zone_clear_data': 'सभी डेटा साफ़ करें',
          'settings_danger_zone_clear_confirm_title': 'डेटा साफ़ करें',
          'settings_danger_zone_clear_confirm_content':
              'क्या आप वाकई सभी रिकॉर्ड हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती है।',
          'about_description':
              'स्कोरडक एक सरल और सुरुचिपूर्ण स्कोर ट्रैकर है। आपको सबसे शुद्ध और सबसे कुशल अनुभव प्रदान करने के लिए समर्पित है।',
          'about_privacy_safety': 'गोपनीयता और सुरक्षा',
          'about_privacy_offline':
              'ऑफ़लाइन चलता है, इंटरनेट अनुमति की आवश्यकता नहीं है',
          'about_privacy_no_cloud':
              'कोई क्लाउड अपलोड नहीं, कोई सर्वर शामिल नहीं है',
          'about_privacy_local':
              'स्थानीय भंडारण, आपका डेटा आपका है',
          'about_feedback_support': 'प्रतिक्रिया और समर्थन',
        },
        'ar': {
          'app_name': 'سكوردك',
          'common_cancel': 'إلغاء',
          'common_done': 'تم',
          'common_save': 'حفظ',
          'common_delete': 'حذف',
          'common_confirm': 'تأكيد',
          'common_edit': 'تعديل',
          'common_share': 'مشاركة',
          'common_unknown': 'غير معروف',
          'home_tab_title': 'ألعاب',
          'home_title': 'سكوردك',
          'home_no_games': 'لا توجد ألعاب',
          'home_start_first_game': 'ابدأ لعبتك الأولى',
          'home_create_game': 'لعبة جديدة',
          'home_game_count': '{}' ' ألعاب',
          'home_player_count': '{}' ' لاعبين',
          'create_game_title': 'إنشاء لعبة',
          'create_game_start': 'بدء',
          'create_game_basic_info': 'معلومات أساسية',
          'create_game_game_name': 'اسم اللعبة',
          'create_game_game_name_placeholder': 'أدخل اسم اللعبة',
          'create_game_player_count': 'اللاعبون',
          'create_game_player_list': 'قائمة اللاعبين',
          'create_game_player_name_placeholder': 'أدخل اسم اللاعب',
          'create_game_default_game_name': 'لعبة جديدة',
          'create_game_default_player_name': 'اللاعب {}',
          'game_detail_found_no_game': 'اللعبة غير موجودة',
          'game_detail_leaderboard': 'لوحة المتصدرين',
          'game_detail_current_score': 'النتيجة المباشرة',
          'game_detail_round_count': '{}' ' جولات',
          'game_detail_leading': 'متصدر',
          'game_detail_round_n': 'الجولة {}',
          'game_detail_no_rounds': 'لا توجد سجلات',
          'game_detail_start_scoring': 'انقر على الزر لبدء التسجيل',
          'game_detail_share_text': 'تحقق من نتيجتنا المباشرة!',
          'game_detail_add_round': 'تسجيل الجولة',
          'game_detail_edit_round': 'تعديل الجولة',
          'game_detail_base_score': 'النتيجة الأساسية',
          'game_detail_step_size': 'حجم الخطوة',
          'game_detail_current_round_score': 'نتيجة الجولة',
          'settings_tab_title': 'الإعدادات',
          'settings_title': 'الإعدادات',
          'settings_appearance': 'المظهر',
          'settings_theme_mode': 'وضع السمة',
          'settings_theme_system': 'النظام',
          'settings_theme_light': 'فاتح',
          'settings_theme_dark': 'داكن',
          'settings_language_title': 'اللغة',
          'settings_language_en': 'English',
          'settings_language_zh_Hans': 'Simplified Chinese',
          'settings_language_zh_Hant': 'Traditional Chinese',
          'settings_language_es': 'الإسبانية',
          'settings_language_fr': 'الفرنسية',
          'settings_language_de': 'الألمانية',
          'settings_language_hi': 'الهندية',
          'settings_language_ar': 'العربية',
          'settings_language_system': 'النظام',
          'settings_about_title': 'حول',
          'settings_about_about_app': 'حول سكوردك',
          'settings_about_version': 'الإصدار',
          'settings_support_title': 'الملاحظات والدعم',
          'settings_support_feedback': 'الملاحظات',
          'settings_support_feedback_subject': 'ملاحظات تطبيق سكوردك (الإصدار: {version})',
          'settings_support_more_apps': 'المزيد من التطبيقات',
          'settings_support_follow_author': 'متابعة المؤلف',
          'settings_danger_zone_title': 'منطقة الخطر',
          'settings_danger_zone_clear_data': 'مسح جميع البيانات',
          'settings_danger_zone_clear_confirm_title': 'مسح البيانات',
          'settings_danger_zone_clear_confirm_content':
              'هل أنت متأكد أنك تريد حذف جميع السجلات؟ لا يمكن التراجع عن هذا الإجراء.',
          'about_description':
              'سكوردك هو متتبع نقاط بسيط وأنيق. مكرس ليوفر لك أنقى وأكثر التجارب كفاءة.',
          'about_privacy_safety': 'الخصوصية والأمان',
          'about_privacy_offline':
              'يعمل دون اتصال بالإنترنت، لا يتطلب إذن الإنترنت',
          'about_privacy_no_cloud':
              'لا يوجد تحميل سحابي، لا يوجد خادم مشترك',
          'about_privacy_local':
              'تخزين محلي، بياناتك ملك لك',
          'about_feedback_support': 'الملاحظات والدعم',
        },
      };
}